pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'aws ec2 run-instances --image-id ami-0f34c5ae932e6f0e4 --instance-type t2.micro --key-name my-keypair --security-group-ids sg-0f124803c76014a13 --subnet-id subnet-07adbb6e18993b024 --region us-east-1'

                
            }
        }
    }
}