pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'aws s3 cp ${WORKSPACE}/S3Copy/b.html s3://test2ani-bucket/b.html'
            }
        }
    }
}